name: agadir-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy>=1.24.1
  - pandas>=1.5.2
  - pytest>=8.1.1
  - ipykernel
  # Development additions
  - jupyter
  - matplotlib>=3.7.0
  - notebook
  # Code quality tools
  - black>=24.1.0
  - flake8>=7.0.0
  - isort>=5.13.0
  - mypy>=1.8.0
  # Enhanced development experience
  - ipython
  - pre-commit>=3.5.0